version: "3"
services:
  cp_zookeeper:
    container_name: cp_zookeeper
    image: confluentinc/cp-zookeeper:7.2.0
    hostname: cp_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_DATA_DIR: "/tmp/data/zookeeper"
      KAFKA_OPTS:  -Dzookeeper.4lw.commands.whitelist=*
    healthcheck:
      test: echo ruok | nc 127.0.0.1 2181 || exit -1
      interval: 5s
      timeout: 10s
      start_period: 10s

  cp_kafka:
    container_name: cp_kafka
    image: confluentinc/cp-kafka:7.2.0
    hostname: cp_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "0"
      KAFKA_ZOOKEEPER_CONNECT: "cp_zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://cp_kafka:9092"
    depends_on:
      - cp_zookeeper
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  cp_kafka_topic_setup:
    container_name: cp_kafka_topic_setup
    image: confluentinc/cp-kafka:7.2.0
    hostname: cp_kafka_topic_setup
    entrypoint: ['']
    command:
      - sh
      - -c
      - |
        while ! nc -z cp_kafka 9092; do sleep 3; done
        kafka-topics --create --bootstrap-server cp_kafka:9092 --topic example
    depends_on:
      - cp_kafka
