version: '3.9'

services:
  jaeger:
    hostname: jaegar
    image: 'jaegertracing/all-in-one:1.35'
    container_name: jaegar
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'

  pyroscope:
    hostname: pyroscope
    image: 'pyroscope/pyroscope:0.22.1'
    container_name: pyroscope
    environment:
      - PYROSCOPE_CONFIG=/pyroscope.yaml
      - PYROSCOPE_LOG_LEVEL=debug
    ports:
      - '4040:4040'
    volumes:
      - ./deployment/local/pyroscope.yaml:/pyroscope.yaml
    command:
      - 'server'
  
  jaeger-ui:
    build:
      context: ''
      dockerfile: ./deployment/local/jaeger-ui.Dockerfile
    hostname: jaegar-ui
    container_name: jaegar-ui
    ports:
      - '4000:3000'
  
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.37.0
    ports:
      - "9090:9090"
  
  app:
    build:
      context: '.'
      dockerfile: ./Dockerfile
    container_name: app
    hostname: app

